jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"

securityRealm:
  local:
    allowsSignup: false
    users:
      - id: "admin"
        password: "Password123!"
        
authorizationStrategy:
  loggedInUsersCanDoAnything:
    allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github"
              username: "devsecops14"
              password: "dev14secops#"
              description: "GitHub Credentials"

jobs:
  - script: >
      pipelineJob('4danimals') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url 'https://github.com/devsecops14/4danimals19052024/tree/master/4danimals18052024'
                  credentialsId 'github'
                }
                branches {
                  name '*/main'
                }
                scriptPath 'Jenkinsfile'
              }
            }
          }
        }
      }
